package com.example.backend.entities.enums;

public enum PrivilegeType {

    PRIVILEGE_LOGIN,
    PRIVILEGE_AUTHENTICATE,
    PRIVILEGE_READ,
    PRIVILEGE_AUTHORIZED,
    PRIVILEGE_PARTICIPATE,
    PRIVILEGE_REPORT,
    PRIVILEGE_SAVE_INFO,
    PRIVILEGE_DELETE,
    PRIVILEGE_UPDATE,
    PRIVILEGE_CREATE,
    PRIVILEGE_LOAD,
    PRIVILEGE_ENDING,
    PRIVILEGE_VALIDATOR,
    PRIVILEGE_SUPERVISOR;
}
