package com.example.backend.entities.users;

public enum PrivilegeType {

    PRIVILEGE_LOGIN,
    PRIVILEGE_READ,
    PRIVILEGE_PARTICIPATE,
    PRIVILEGE_DELETE,
    PRIVILEGE_UPDATE,
    PRIVILEGE_CREATE,
    PRIVILEGE_LOAD,
    PRIVILEGE_ENDING,
    PRIVILEGE_VALIDATOR,
    PRIVILEGE_SUPERVISOR
}
